PierresTreats/Models/Flavor.cs
using System.Collections.Generic;

namespace PierresTreats.Models
{
  public class Flavor
  {
    public Flavor()
    {
      this.JoinEntities = new HashSet<FlavorTreat>();
    }

    public int FlavorId { get; set; }
    public string Name { get; set; }

    public virtual ICollection<FlavorTreat> JoinEntities { get;}
  }
}

PierresTreats/Controllers/FlavorsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Security.Claims;
using System.Linq;
using PierresTreats.Models;

namespace PierresTreats.Controllers
{
  [Authorize]
  public class FlavorsController : Controller
  {
    private readonly PierresTreatsContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public FlavorsController(UserManager<ApplicationUser> userManager, PierresTreatsContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    [AllowAnonymous]
    public  ActionResult Index()
    {
      var treats = _db.Flavors.ToList();
      return View(treats);
    }
    
    [AllowAnonymous]
    public ActionResult Details(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Flavor flavor)
    {
      _db.Flavors.Add(flavor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Edit(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }

    [HttpPost]
    public ActionResult Edit(Flavor flavor)
    {
      _db.Entry(flavor).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddTreat(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "Name");
      return View(thisFlavor);
    }

    [HttpPost]
    public ActionResult AddTreat(Flavor flavor, int TreatId)
    {
      if (TreatId != 0)
      {
        _db.FlavorTreat.Add(new FlavorTreat() { TreatId = TreatId, FlavorId = flavor.FlavorId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      _db.Flavors.Remove(thisFlavor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteTreat(int joinId)
    {
      var joinEntry = _db.FlavorTreat.FirstOrDefault(entry => entry.FlavorTreatId == joinId);
      _db.FlavorTreat.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

PierresTreats/Views/Flavors/AddTreat.cshtml
@model PierresTreats.Models.Flavor

<h2>Add a Treat</h2>

<h4>Add a treat that contains this flavor: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.FlavorId)

  @Html.Label("Select treat")
  @Html.DropDownList("TreatId")

  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to list", "Index")</p>

PierresTreats/Views/Flavors/Create.cshtml
@model PierresTreats.Models.Flavor

<h4>Add a new Flavor</h4>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)

  <input type="submit" value="Add new flavor"/>
}
<p>@Html.ActionLink("Show all flavors", "Index")</p>

PierresTreats/Views/Flavors/Delete.cshtml
@model PierresTreats.Models.Flavor

<h2>Are you sure you want to delete this Flavor?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

PierresTreats/Views/Flavors/Details.cshtml
@model PierresTreats.Models.Flavor

<h2>Flavor Details</h2>

<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>

@if(@Model.JoinEntities.Count == 0)
{
  <p>There are no treats with this flavor</p>
}
else
{
  <h4>Treats with this Flavor: </h4>
  <ul>
  @foreach(var join in Model.JoinEntities)
  {
    <li>@join.Treat.Name</li>
    @using (Html.BeginForm("DeleteTreat", "Flavors"))
    {
      @Html.Hidden("joinId", @join.FlavorTreatId)
      <input type="submit" value="Delete"/>
    }
  }
  </ul>
}

<p>@Html.ActionLink("Add a Treat", "AddTreat", new { id = Model.FlavorId })</p>
<p>@Html.ActionLink("Back to list", "Index")</p>
<p>@Html.ActionLink("Edit Flavor", "Edit", new { id = Model.FlavorId })</p>

PierresTreats/Views/Flavors/Edit.cshtml
@model PierresTreats.Models.Flavor

<h4>Edit @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.FlavorId)

  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)

  <input type="submit" value="Save"/>
}
<p>@Html.ActionLink("Show all flavors", "Index")</p>

PierresTreats/Views/Flavors/Index.cshtml
@using PierresTreats.Models;
@model IEnumerable<PierresTreats.Models.Flavor>

<h1>Flavors</h1>

@if (Model.Any())
{
  <ul>
    @foreach (Flavor flavor in Model)
    {
      <li>@Html.ActionLink($"{flavor.Name}", "Details", new { id = flavor.FlavorId })</li>
    }
  </ul>
} 
else
{
  <h3>No flavors have been added yet!</h3>
}

<p>@Html.ActionLink("Add new flavor", "Create")</p>